name: rotary_scrollbar
description: flutter scrollbar for wearOS devices with round screens.
version: 0.1.0
homepage: https://github.com/hyperfluid-tech/rotary_scrollbar

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  wearable_rotary: ^2.0.0
  vibration: ^1.7.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
